# BoatmanMode Configuration
# Copy this to ~/.boatman.yaml or .boatman.yaml in your project

# Linear API key (or set LINEAR_API_KEY env var)
# linear_key: lin_api_xxxxx

# Claude CLI tools (enables agent tool capabilities)
enable_tools: true     # Enable Claude CLI tool capabilities (default: true)

# Workflow settings
max_iterations: 5      # Max review/refactor cycles before giving up (default: 5)
base_branch: main      # Base branch for worktrees
auto_pr: true          # Automatically create PR on success

# Review pass criteria (more lenient defaults)
review:
  max_critical_issues: 1           # Max critical issues to still pass (default: 1)
  max_major_issues: 3              # Max major issues to still pass (default: 3)
  min_verification_confidence: 50   # Min confidence % for diff verification (default: 50)
  strict_parsing: false            # Enable strict keyword parsing for reviews (default: false)

# Claude CLI settings
claude:
  command: claude                     # Claude CLI command
  use_tmux: false                     # Use tmux for large prompts
  large_prompt_threshold: 100000      # Character count for tmux
  timeout: 0                          # 0 = no timeout
  enable_prompt_caching: true         # Enable prompt caching (reduces costs 50-90%)

  # Multi-model strategy: Use different models per agent type
  # Available models: claude-opus-4-6, claude-sonnet-4.5, claude-haiku-4
  # Leave empty to use the Claude CLI default model
  models:
    planner: claude-sonnet-4.5       # Complex planning & codebase analysis
    executor: claude-sonnet-4.5      # Code generation
    reviewer: claude-sonnet-4.5      # Quality review
    refactor: claude-sonnet-4.5      # Fixing review issues
    preflight: claude-haiku-4        # Fast validation (90% cheaper)
    test_runner: claude-haiku-4      # Simple test output parsing (90% cheaper)

# Prerequisites (no config needed - just make sure they're installed & auth'd):
# - claude CLI (authenticated via gcloud / Vertex AI)
# - gh CLI (authenticated via `gh auth login`)
# - git (with push access to your repo)
